version: '3.4'

services:
  db:
    container_name: nextcloud_db
    image: postgres
    restart: unless-stopped
    volumes:
      - ./nextcloud-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    networks:
      - nextcloud_internal
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user

  app:
    container_name: nextcloud_app
    image: nextcloud
    restart: unless-stopped
    ports:
      - 42069:80
    volumes:
      - ./nextcloud-config:/var/www/html/config
      - ./nextcloud-data:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
    depends_on:
      - db
    networks:
      - nextcloud_internal
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user


networks:
  nextcloud_internal:

secrets:
  nextcloud_admin_password:
    file: ./.secrets/nextcloud_admin_password.txt # put admin password to this file
  nextcloud_admin_user:
    file: ./.secrets/nextcloud_admin_user.txt # put admin username to this file
  postgres_db:
    file: ./.secrets/postgres_db.txt # put postgresql db name to this file
  postgres_password:
    file: ./.secrets/postgres_password.txt # put postgresql password to this file
  postgres_user:
    file: ./.secrets/postgres_user.txt # put postgresql username to this file