version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD="some very secure password!!!"
      - MYSQL_PASSWORD="less secure password"
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=ref_db

  app:
    image: nextcloud
    restart: always
    ports:
      - 42069:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD="some very secure password!!!"
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=ref_db
      - MYSQL_HOST=db
